### ISSUE TITLE
管理表 保存失败

### ISSUE THREAD

**Issue by JoffreyN** [dongsuo/vue-data-board#73]
```python
Internal Server Error: /api/source/tables/save
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python38\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\zp\mystuff\vueDataBoard\py_vislib\vislib\views\source.py", line 154, in sourceTableSave
    table_alias=table['table_alias'],
KeyError: 'table_alias'
```

**Comment by JoffreyN** [comment]
![image](https://user-images.githubusercontent.com/31299103/138203263-60b8e511-5712-4dc8-8d7b-8527c5407185.png)

不知道这个别名是干啥的，我直接改成等于表名了
